name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Triggert de bouw telkens als je iets aanpast in 'main'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java (Nodig voor Flutter)
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Genereer missende web-bestanden
        run: flutter create . --platforms web

      - name: Installeer dependencies
        run: flutter pub get

      - name: Bouw de Web App
        run: flutter build web --base-href "/${{ github.event.repository.name }}/"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/web

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
