name: Bouw webOS App (.ipk)

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js (Nodig voor LG Tools)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Installeer LG webOS CLI Tools
        run: npm install -g @webosose/ares-cli

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Genereer web-bestanden
        run: flutter create . --platforms web

      - name: Installeer dependencies
        run: flutter pub get

      - name: Bouw de Flutter Web basis
        run: flutter build web --release

      - name: Configureer webOS App Bestanden
        run: |
          # Zorg dat de build map er is en kopieer een van je afbeeldingen als app-icoon
          mkdir -p build/web
          cp assets/images/0VCil-removebg-preview.png build/web/icon.png
          
          # Maak het verplichte appinfo.json bestand aan voor webOS
          cat <<EOF > build/web/appinfo.json
          {
              "id": "com.jordy.webostvoverlay",
              "version": "1.0.0",
              "vendor": "Jordy",
              "type": "web",
              "main": "index.html",
              "title": "Match Overlay WK",
              "icon": "icon.png"
          }
          EOF

      - name: Verpak de app tot webOS .ipk bestand
        run: |
          ares-package build/web -o .

      - name: Upload het .ipk bestand naar GitHub
        uses: actions/upload-artifact@v4
        with:
          name: webos-app-package
          path: "*.ipk"
          
